#!/bin/bash
set -e
# For now, no hooks
# OPTIONS="-c gcc-hooks"
parsecmgmt -a build -p blackscholes $OPTIONS
parsecmgmt -a build -p bodytrack $OPTIONS
parsecmgmt -a build -p canneal $OPTIONS
parsecmgmt -a build -p swaptions $OPTIONS
parsecmgmt -a build -p streamcluster $OPTIONS
parsecmgmt -a build -p fluidanimate $OPTIONS
parsecmgmt -a build -p ferret $OPTIONS
parsecmgmt -a build -p freqmine $OPTIONS
parsecmgmt -a build -p x264 $OPTIONS
parsecmgmt -a build -p splash2x.barnes $OPTIONS
parsecmgmt -a build -p splash2x.fmm $OPTIONS
parsecmgmt -a build -p splash2x.ocean_cp $OPTIONS
parsecmgmt -a build -p splash2x.ocean_ncp $OPTIONS
parsecmgmt -a build -p splash2x.radiosity $OPTIONS
parsecmgmt -a build -p splash2x.raytrace $OPTIONS
parsecmgmt -a build -p splash2x.water_nsquared $OPTIONS
parsecmgmt -a build -p splash2x.water_spatial $OPTIONS
parsecmgmt -a build -p splash2x.cholesky $OPTIONS
parsecmgmt -a build -p splash2x.fft $OPTIONS
parsecmgmt -a build -p splash2x.radix $OPTIONS
parsecmgmt -a build -p splash2x.raytrace $OPTIONS
parsecmgmt -a build -p splash2x.lu_cb $OPTIONS
parsecmgmt -a build -p splash2x.lu_ncb $OPTIONS
