#!/bin/ash
######################################################################################
# Command lines to launch the SMALL/MEDIUM/LARGE benchmarks with our directory organization #
######################################################################################

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
then
    echo "./parsec_exec small|large nthreads parsec_name"
	exit 1
fi
#echo "ADD XOR INSTRUCTION"
#./XOR/xor #ADD THE XOR INSTRUCTION

NTHREADS="$2"

if [ "$3" = "barnes" ]
then
    if [ "$1" = "small" ]
    then
	cat ext/splash2x/apps/barnes/inputs/input.template | sed -e "s/NUMPROCS/${NTHREADS}/" | bin/barnes ${NTHREADS}
    elif [ "$1" = "large" ]
    then
	cat ext/splash2x/apps/barnes/inputs/input.template | sed -e "s/NUMPROCS/${NTHREADS}/" | time -p bin/barnes ${NTHREADS}

    fi
elif [ "$3" = "blackscholes" ]
then
    if [ "$1" = "small" ]
    then
	bin/blackscholes ${NTHREADS} pkgs/apps/blackscholes/inputs/in_4K.txt prices.txt
    elif [ "$1" = "large" ]
    then
	time -p bin/blackscholes ${NTHREADS} pkgs/apps/blackscholes/inputs/in_64K.txt prices.txt
    fi

elif [ "$3" = "bodytrack" ]
then
    if [ "$1" = "small" ]
    then	
	bin/bodytrack pkgs/apps/bodytrack/inputs/sequenceB_1 4 1 1000 5 0 ${NTHREADS}
    elif [ "$1" = "large" ]
    then
	time -p bin/bodytrack pkgs/apps/bodytrack/inputs/sequenceB_4 4 4 4000 5 0 ${NTHREADS}
    fi

elif [ "$3" = "cholesky" ]
then
    if [ "$1" = "small" ]
    then	
	bin/cholesky -p${NTHREADS} ext/splash2x/kernels/cholesky/inputs/tk29.O
    elif [ "$1" = "large" ]
    then
	time -p bin/cholesky -p${NTHREADS} ext/splash2x/kernels/cholesky/inputs/tk29.O
    fi

elif [ "$3" = "fft" ]
then
    if [ "$1" = "small" ]
    then	
	bin/fft -p${NTHREADS} -m20
    elif [ "$1" = "large" ]
    then
	if [ "$2" = "64" ] || [ "$2" = "32" ] || [ "$2" = "16" ]
	then
	    time -p bin/fft -p${NTHREADS} -m24
	fi
    fi

elif [ "$3" = "fluidanimate" ]
then
    if [ "$1" = "small" ]
    then	
	bin/fluidanimate ${NTHREADS} 5 pkgs/apps/fluidanimate/inputs/in_35K.fluid out.fluid
    elif [ "$1" = "large" ]
    then
	if [ "$2" -ne "24" ] && [ "$2" -ne "48" ] && [ "$2" -ne "96" ]
	then
	    time -p bin/fluidanimate ${NTHREADS} 5 pkgs/apps/fluidanimate/inputs/in_300K.fluid out.fluid
	fi
    fi

elif [ "$3" = "freqmine" ]
then
    if [ "$1" = "small" ]
    then	
	OMP_NUM_THREADS=${NTHREADS} bin/freqmine pkgs/apps/freqmine/inputs/kosarak_250k.dat 220
    elif [ "$1" = "large" ]
    then
	OMP_NUM_THREADS=${NTHREADS} time -p bin/freqmine pkgs/apps/freqmine/inputs/kosarak_990k.dat 790
    fi

elif [ "$3" = "lu_cb" ]
then
    if [ "$1" = "small" ]
    then	
	bin/lu_cb -p${NTHREADS} -n512 -b16
    elif [ "$1" = "large" ]
    then
	time -p bin/lu_cb -p${NTHREADS} -n2048 -b16
    fi

elif [ "$3" = "lu_ncb" ]
then
    if [ "$1" = "small" ]
    then	
	bin/lu_ncb -p${NTHREADS} -n512 -b16
    elif [ "$1" = "large" ]
    then	
        time -p bin/lu_ncb -p${NTHREADS} -n2048 -b16
    fi

elif [ "$3" = "ocean_cp" ]
then
    if [ "$1" = "small" ]
    then	
	bin/ocean_cp -p${NTHREADS} -n514 -e1e-07 -r20000 -t28800
    elif [ "$1" = "large" ]
    then
	if [ "$2" -ne "24" ] && [ "$2" -ne "48" ] && [ "$2" -ne "96" ]
	then
	    time -p bin/ocean_cp -p${NTHREADS} -n2050 -e1e-07 -r20000 -t28800
	fi
    fi

elif [ "$3" = "ocean_ncp" ]
then
    if [ "$1" = "small" ]
    then	
	bin/ocean_ncp -p${NTHREADS} -n514 -e1e-07 -r20000 -t28800
    elif [ "$1" = "large" ]
    then
	if [ "$2" -ne "24" ] && [ "$2" -ne "48" ] && [ "$2" -ne "96" ]
	then
	    time -p bin/ocean_ncp -p${NTHREADS} -n2050 -e1e-07 -r20000 -t28800
	fi
    fi

elif [ "$3" = "swaptions" ]
then
    if [ "$1" = "small" ]
    then	
	# a=17
	# if [ "${NTHREADS}" -lt "$a" ]
	# then
	    bin/swaptions -ns  ${NTHREADS} -sm 10000 -nt ${NTHREADS}
	# else
	# 	echo ${NTHREADS}  "> 16"
	# fi    elif [ "$1" = "large" ]
	if [ "$2" -ne "24" ] && [ "$2" -ne "48" ] && [ "$2" -ne "96" ]
	then
	    time -p bin/swaptions -ns 64 -sm 40000 -nt ${NTHREADS}
	fi
fi
elif [ "$3" = "water_nsquared" ]
then
    if [ "$1" = "small" ]
    then	
	(cd ext/splash2x/apps/water_nsquared/inputs; cat input.template | sed  -e "s/NUMPROCS/${NTHREADS}/" | /root/bin/water_nsquared)
    elif [ "$1" = "large" ]
    then
	(cd ext/splash2x/apps/water_nsquared/inputs; cat input.template | sed  -e "s/NUMPROCS/${NTHREADS}/" | time -p /root/bin/water_nsquared)
    fi

elif [ "$3" = "water_spatial" ]
then
    if [ "$1" = "small" ]
    then	
	(cd ext/splash2x/apps/water_spatial/inputs; cat input.template | sed  -e "s/NUMPROCS/${NTHREADS}/" | /root/bin/water_spatial)
    elif [ "$1" = "large" ]
    then
	(cd ext/splash2x/apps/water_spatial/inputs; cat input.template | sed  -e "s/NUMPROCS/${NTHREADS}/" | time -p /root/bin/water_spatial)
    fi

elif [ "$3" = "radix" ]
then
    if [ "$1" = "small" ]
    then	
	bin/radix -p${NTHREADS} -r4096 -n4194304 -m2147483647
    elif [ "$1" = "large" ]
    then
	if [ "$2" -ne "24" ] && [ "$2" -ne "48" ] && [ "$2" -ne "96" ]
	then
	    time -p bin/radix -p${NTHREADS} -r4096 -n67108864 -m2147483647
	fi
    fi
elif [ "$3" = "ferret" ]
then
    if [ "$1" = "small" ]
    then
    	(cd pkgs/apps/ferret/inputs; ~bin/ferret corel lsh queries 10 20 ${NTHREADS} output.txt)
    elif [ "$1" = "large" ]
    then
	if [ "$2" -ne "24" ] && [ "$2" -ne "48" ] && [ "$2" -ne "96" ]
	then
	    (cd pkgs/apps/ferret/inputs; time -p ~/bin/ferret corel lsh queries 10 20 ${NTHREADS} output.txt)
	fi
    fi
fi
